// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import EmptyController from "./empty_controller"
application.register("empty", EmptyController)

import FreezerController from "./freezer_controller"
application.register("freezer", FreezerController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NoformController from "./noform_controller"
application.register("noform", NoformController)

import PusherController from "./pusher_controller"
application.register("pusher", PusherController)

import SelectorController from "./selector_controller"
application.register("selector", SelectorController)

import TimestampController from "./timestamp_controller"
application.register("timestamp", TimestampController)

import ViewerController from "./viewer_controller"
application.register("viewer", ViewerController)

import VisibleController from "./visible_controller"
application.register("visible", VisibleController)

import VisitorController from "./visitor_controller"
application.register("visitor", VisitorController)
